### ISSUE TITLE
Can't move the window in the OS X after update to v6.3.0

### ISSUE THREAD

**Issue by vikiyi0** [poooi/poi#1062] opened 2016-06-11 03:42 UTC
Can't move the window in the OS X after update to v6.3.0

my OS X version is 10.11.5

**Comment by taroxd** [comment] 2016-06-11 03:42
Dupe of #1056

**Comment by yukixz** [comment] 2016-06-11 03:42
Fixed in 6.3.1. Try using https://github.com/poooi/poi/tree/v6.3.1-beta.0

**Closed** 2016-06-11 03:42 UTC
